// lib/services/navigation_graph.dart
import 'dart:ui';

class NavNode {
  final String id;
  final Offset pos;
  const NavNode(this.id, this.pos);
}

class NavEdge {
  final String from;
  final String to;
  final bool blocked;
  const NavEdge(this.from, this.to, {this.blocked = false});
}

class NavigationGraph {
  static const List<NavNode> groundNodes = [
    NavNode('gf_entry_driveway', Offset(0.468, 0.950)),
    NavNode('gf_entry_top', Offset(0.468, 0.068)),
    NavNode('gf_entry_stairs_left', Offset(0.065, 0.305)),
    NavNode('gf_entry_stairs_right', Offset(0.935, 0.305)),
    NavNode('gf_h_far_left', Offset(0.030, 0.305)),
    NavNode('gf_h_left_1', Offset(0.100, 0.305)),
    NavNode('gf_h_left_2', Offset(0.180, 0.305)),
    NavNode('gf_h_left_3', Offset(0.255, 0.305)),
    NavNode('gf_h_left_4', Offset(0.325, 0.305)),
    NavNode('gf_h_left_5', Offset(0.385, 0.305)),
    NavNode('gf_h_center_l', Offset(0.420, 0.305)),
    NavNode('gf_h_spine', Offset(0.468, 0.305)),
    NavNode('gf_h_center_r', Offset(0.510, 0.305)),
    NavNode('gf_h_right_1', Offset(0.565, 0.305)),
    NavNode('gf_h_right_2', Offset(0.620, 0.305)),
    NavNode('gf_h_right_3', Offset(0.700, 0.305)),
    NavNode('gf_h_right_4', Offset(0.775, 0.305)),
    NavNode('gf_h_right_5', Offset(0.850, 0.305)),
    NavNode('gf_h_right_6', Offset(0.920, 0.305)),
    NavNode('gf_h_far_right', Offset(0.970, 0.305)),
    NavNode('gf_v_top', Offset(0.468, 0.068)),
    NavNode('gf_v_upper', Offset(0.468, 0.200)),
    NavNode('gf_v_mid_upper', Offset(0.468, 0.265)),
    NavNode('gf_v_mid_lower', Offset(0.468, 0.365)),
    NavNode('gf_v_lobby_top', Offset(0.468, 0.430)),
    NavNode('gf_v_lobby_mid', Offset(0.468, 0.530)),
    NavNode('gf_v_lobby_bot', Offset(0.468, 0.640)),
    NavNode('gf_v_entrance', Offset(0.468, 0.760)),
    NavNode('gf_v_driveway', Offset(0.468, 0.950)),
    NavNode('gf_room_ics', Offset(0.130, 0.200)),
    NavNode('gf_room_training', Offset(0.185, 0.200)),
    NavNode('gf_room_ihs', Offset(0.240, 0.200)),
    NavNode('gf_room_ibfs', Offset(0.295, 0.200)),
    NavNode('gf_room_ite', Offset(0.360, 0.200)),
    NavNode('gf_room_restroom_top_left', Offset(0.090, 0.200)),
    NavNode('gf_room_toilet_left', Offset(0.060, 0.200)),
    NavNode('gf_room_cr_left1', Offset(0.170, 0.140)),
    NavNode('gf_room_cr_left2', Offset(0.195, 0.140)),
    NavNode('gf_room_ias', Offset(0.468, 0.200)),
    NavNode('gf_room_restroom_top_center', Offset(0.468, 0.140)),
    NavNode('gf_room_medical', Offset(0.640, 0.200)),
    NavNode('gf_room_restroom_top_right', Offset(0.920, 0.200)),
    NavNode('gf_room_mb105', Offset(0.730, 0.200)),
    NavNode('gf_room_mb103', Offset(0.790, 0.200)),
    NavNode('gf_room_mpr', Offset(0.840, 0.200)),
    NavNode('gf_room_midwifery', Offset(0.890, 0.200)),
    NavNode('gf_room_pfom', Offset(0.960, 0.200)),
    NavNode('gf_room_cr_right1', Offset(0.900, 0.140)),
    NavNode('gf_room_cr_right2', Offset(0.925, 0.140)),
    NavNode('gf_room_toilet_right1', Offset(0.870, 0.140)),
    NavNode('gf_room_toilet_right2', Offset(0.980, 0.140)),
    NavNode('gf_room_icje', Offset(0.100, 0.420)),
    NavNode('gf_room_sldo', Offset(0.030, 0.370)),
    NavNode('gf_room_crim_lab', Offset(0.185, 0.420)),
    NavNode('gf_room_vp_admin', Offset(0.305, 0.420)),
    NavNode('gf_room_registrar', Offset(0.375, 0.420)),
    NavNode('gf_room_record', Offset(0.438, 0.420)),
    NavNode('gf_room_scholarship', Offset(0.440, 0.460)),
    NavNode('gf_room_ojt', Offset(0.440, 0.530)),
    NavNode('gf_room_accreditation', Offset(0.595, 0.490)),
    NavNode('gf_room_ciso', Offset(0.610, 0.420)),
    NavNode('gf_room_avr', Offset(0.690, 0.420)),
    NavNode('gf_room_dressing', Offset(0.760, 0.420)),
    NavNode('gf_room_music', Offset(0.825, 0.420)),
    NavNode('gf_room_dance', Offset(0.890, 0.420)),
    NavNode('gf_room_barracks', Offset(0.960, 0.420)),
    NavNode('gf_room_main_lobby', Offset(0.595, 0.530)),
    NavNode('gf_room_elevator', Offset(0.468, 0.365)),
  ];

  static const List<NavEdge> groundEdges = [
    NavEdge('gf_h_far_left', 'gf_h_left_1'),
    NavEdge('gf_h_left_1', 'gf_h_left_2'),
    NavEdge('gf_h_left_2', 'gf_h_left_3'),
    NavEdge('gf_h_left_3', 'gf_h_left_4'),
    NavEdge('gf_h_left_4', 'gf_h_left_5'),
    NavEdge('gf_h_left_5', 'gf_h_center_l'),
    NavEdge('gf_h_center_l', 'gf_h_spine'),
    NavEdge('gf_h_spine', 'gf_h_center_r'),
    NavEdge('gf_h_center_r', 'gf_h_right_1'),
    NavEdge('gf_h_right_1', 'gf_h_right_2'),
    NavEdge('gf_h_right_2', 'gf_h_right_3'),
    NavEdge('gf_h_right_3', 'gf_h_right_4'),
    NavEdge('gf_h_right_4', 'gf_h_right_5'),
    NavEdge('gf_h_right_5', 'gf_h_right_6'),
    NavEdge('gf_h_right_6', 'gf_h_far_right'),
    NavEdge('gf_entry_stairs_left', 'gf_h_far_left'),
    NavEdge('gf_entry_stairs_right', 'gf_h_far_right'),
    NavEdge('gf_entry_top', 'gf_v_top'),
    NavEdge('gf_v_top', 'gf_v_upper'),
    NavEdge('gf_v_upper', 'gf_v_mid_upper'),
    NavEdge('gf_v_mid_upper', 'gf_h_spine'),
    NavEdge('gf_h_spine', 'gf_v_mid_lower'),
    NavEdge('gf_v_mid_lower', 'gf_room_elevator'),
    NavEdge('gf_v_mid_lower', 'gf_v_lobby_top'),
    NavEdge('gf_v_lobby_top', 'gf_v_lobby_mid'),
    NavEdge('gf_v_lobby_mid', 'gf_v_lobby_bot'),
    NavEdge('gf_v_lobby_bot', 'gf_v_entrance'),
    NavEdge('gf_v_entrance', 'gf_v_driveway'),
    NavEdge('gf_v_driveway', 'gf_entry_driveway'),
    NavEdge('gf_h_left_5', 'gf_v_mid_lower', blocked: true),
    NavEdge('gf_h_right_1', 'gf_v_mid_lower', blocked: true),
    NavEdge('gf_h_left_1', 'gf_room_ics'),
    NavEdge('gf_h_left_2', 'gf_room_training'),
    NavEdge('gf_h_left_3', 'gf_room_ihs'),
    NavEdge('gf_h_left_4', 'gf_room_ibfs'),
    NavEdge('gf_h_left_5', 'gf_room_ite'),
    NavEdge('gf_h_spine', 'gf_room_ias'),
    NavEdge('gf_room_ias', 'gf_room_restroom_top_center'),
    NavEdge('gf_room_ias', 'gf_v_upper'),
    NavEdge('gf_h_left_1', 'gf_room_restroom_top_left'),
    NavEdge('gf_h_far_left', 'gf_room_toilet_left'),
    NavEdge('gf_h_left_2', 'gf_room_cr_left1'),
    NavEdge('gf_h_left_2', 'gf_room_cr_left2'),
    NavEdge('gf_h_right_2', 'gf_room_medical'),
    NavEdge('gf_h_right_3', 'gf_room_mb105'),
    NavEdge('gf_h_right_4', 'gf_room_mb103'),
    NavEdge('gf_h_right_5', 'gf_room_mpr'),
    NavEdge('gf_h_right_5', 'gf_room_midwifery'),
    NavEdge('gf_h_far_right', 'gf_room_pfom'),
    NavEdge('gf_h_right_6', 'gf_room_restroom_top_right'),
    NavEdge('gf_h_right_6', 'gf_room_cr_right1'),
    NavEdge('gf_h_right_6', 'gf_room_cr_right2'),
    NavEdge('gf_h_right_6', 'gf_room_toilet_right1'),
    NavEdge('gf_h_far_right', 'gf_room_toilet_right2'),
    NavEdge('gf_h_far_left', 'gf_room_sldo'),
    NavEdge('gf_h_left_1', 'gf_room_icje'),
    NavEdge('gf_h_left_2', 'gf_room_crim_lab'),
    NavEdge('gf_h_left_4', 'gf_room_vp_admin'),
    NavEdge('gf_h_left_5', 'gf_room_registrar'),
    NavEdge('gf_h_center_l', 'gf_room_record'),
    NavEdge('gf_v_lobby_top', 'gf_room_scholarship'),
    NavEdge('gf_v_lobby_mid', 'gf_room_ojt'),
    NavEdge('gf_h_center_r', 'gf_room_accreditation'),
    NavEdge('gf_h_right_1', 'gf_room_ciso'),
    NavEdge('gf_h_right_2', 'gf_room_avr'),
    NavEdge('gf_h_right_3', 'gf_room_dressing'),
    NavEdge('gf_h_right_4', 'gf_room_music'),
    NavEdge('gf_h_right_5', 'gf_room_dance'),
    NavEdge('gf_h_far_right', 'gf_room_barracks'),
    NavEdge('gf_v_lobby_mid', 'gf_room_main_lobby'),
  ];

  static const List<NavNode> secondNodes = [
    NavNode('sf_entry_stairs_left', Offset(0.065, 0.500)),
    NavNode('sf_entry_stairs_right', Offset(0.935, 0.500)),
    NavNode('sf_entry_deck', Offset(0.468, 0.950)),
    NavNode('sf_h_far_left', Offset(0.055, 0.415)),
    NavNode('sf_h_left_1', Offset(0.120, 0.415)),
    NavNode('sf_h_left_2', Offset(0.200, 0.415)),
    NavNode('sf_h_left_3', Offset(0.280, 0.415)),
    NavNode('sf_h_left_4', Offset(0.355, 0.415)),
    NavNode('sf_h_left_5', Offset(0.420, 0.415)),
    NavNode('sf_h_left_6', Offset(0.450, 0.415)),
    NavNode('sf_h_spine', Offset(0.468, 0.415)),
    NavNode('sf_h_right_1', Offset(0.490, 0.415)),
    NavNode('sf_h_right_2', Offset(0.540, 0.415)),
    NavNode('sf_h_right_3', Offset(0.600, 0.415)),
    NavNode('sf_h_right_4', Offset(0.670, 0.415)),
    NavNode('sf_h_right_5', Offset(0.750, 0.415)),
    NavNode('sf_h_right_6', Offset(0.830, 0.415)),
    NavNode('sf_h_right_7', Offset(0.900, 0.415)),
    NavNode('sf_h_far_right', Offset(0.950, 0.415)),
    NavNode('sf_v_mid', Offset(0.468, 0.500)),
    NavNode('sf_v_deans', Offset(0.468, 0.580)),
    NavNode('sf_v_vpaa', Offset(0.468, 0.670)),
    NavNode('sf_v_stair_bottom', Offset(0.468, 0.760)),
    NavNode('sf_v_deck', Offset(0.468, 0.860)),
    NavNode('sf_v_deck_bottom', Offset(0.468, 0.950)),
    NavNode('sf_room_guidance_test', Offset(0.045, 0.340)),
    NavNode('sf_room_sub_lobby', Offset(0.090, 0.340)),
    NavNode('sf_room_comp_lab', Offset(0.185, 0.340)),
    NavNode('sf_room_comp_room1', Offset(0.285, 0.340)),
    NavNode('sf_room_comp_room2', Offset(0.360, 0.340)),
    NavNode('sf_room_comp_room3', Offset(0.425, 0.340)),
    NavNode('sf_room_restroom_cl', Offset(0.468, 0.340)),
    NavNode('sf_room_restroom_cr', Offset(0.490, 0.340)),
    NavNode('sf_room_restroom_r1', Offset(0.800, 0.340)),
    NavNode('sf_room_restroom_r2', Offset(0.830, 0.340)),
    NavNode('sf_room_vip_lounge', Offset(0.590, 0.340)),
    NavNode('sf_room_faculty_lounge', Offset(0.740, 0.340)),
    NavNode('sf_room_speech_lab', Offset(0.875, 0.340)),
    NavNode('sf_room_bseed_left', Offset(0.970, 0.340)),
    NavNode('sf_room_bseed_right', Offset(0.970, 0.500)),
    NavNode('sf_room_guidance_counseling', Offset(0.045, 0.500)),
    NavNode('sf_room_moot_court', Offset(0.170, 0.500)),
    NavNode('sf_room_business', Offset(0.295, 0.500)),
    NavNode('sf_room_classroom_l', Offset(0.385, 0.500)),
    NavNode('sf_room_classroom_c', Offset(0.430, 0.500)),
    NavNode('sf_room_classroom_r', Offset(0.460, 0.500)),
    NavNode('sf_room_board', Offset(0.590, 0.500)),
    NavNode('sf_room_hrmo', Offset(0.660, 0.500)),
    NavNode('sf_room_faculty', Offset(0.740, 0.500)),
    NavNode('sf_room_supply', Offset(0.810, 0.500)),
    NavNode('sf_room_vp_planning', Offset(0.870, 0.500)),
    NavNode('sf_room_evp', Offset(0.920, 0.500)),
    NavNode('sf_room_deans', Offset(0.440, 0.620)),
    NavNode('sf_room_vpaa', Offset(0.440, 0.710)),
    NavNode('sf_room_president', Offset(0.595, 0.660)),
    NavNode('sf_room_main_stage', Offset(0.468, 0.130)),
    NavNode('sf_room_bleacher_left', Offset(0.250, 0.200)),
    NavNode('sf_room_bleacher_right', Offset(0.750, 0.200)),
  ];

  static const List<NavEdge> secondEdges = [
    NavEdge('sf_h_far_left', 'sf_h_left_1'),
    NavEdge('sf_h_left_1', 'sf_h_left_2'),
    NavEdge('sf_h_left_2', 'sf_h_left_3'),
    NavEdge('sf_h_left_3', 'sf_h_left_4'),
    NavEdge('sf_h_left_4', 'sf_h_left_5'),
    NavEdge('sf_h_left_5', 'sf_h_left_6'),
    NavEdge('sf_h_left_6', 'sf_h_spine'),
    NavEdge('sf_h_spine', 'sf_h_right_1'),
    NavEdge('sf_h_right_1', 'sf_h_right_2'),
    NavEdge('sf_h_right_2', 'sf_h_right_3'),
    NavEdge('sf_h_right_3', 'sf_h_right_4'),
    NavEdge('sf_h_right_4', 'sf_h_right_5'),
    NavEdge('sf_h_right_5', 'sf_h_right_6'),
    NavEdge('sf_h_right_6', 'sf_h_right_7'),
    NavEdge('sf_h_right_7', 'sf_h_far_right'),
    NavEdge('sf_entry_stairs_left', 'sf_h_far_left'),
    NavEdge('sf_entry_stairs_right', 'sf_h_far_right'),
    NavEdge('sf_h_far_left', 'sf_room_guidance_test', blocked: true),
    NavEdge('sf_h_far_right', 'sf_room_bseed_right', blocked: true),
    NavEdge('sf_h_spine', 'sf_v_mid'),
    NavEdge('sf_v_mid', 'sf_v_deans'),
    NavEdge('sf_v_deans', 'sf_v_vpaa'),
    NavEdge('sf_v_vpaa', 'sf_v_stair_bottom'),
    NavEdge('sf_v_stair_bottom', 'sf_v_deck'),
    NavEdge('sf_v_deck', 'sf_v_deck_bottom'),
    NavEdge('sf_v_deck_bottom', 'sf_entry_deck'),
    NavEdge('sf_h_left_1', 'sf_room_guidance_test'),
    NavEdge('sf_h_left_1', 'sf_room_sub_lobby'),
    NavEdge('sf_h_left_2', 'sf_room_comp_lab'),
    NavEdge('sf_h_left_3', 'sf_room_comp_room1'),
    NavEdge('sf_h_left_4', 'sf_room_comp_room2'),
    NavEdge('sf_h_left_5', 'sf_room_comp_room3'),
    NavEdge('sf_h_spine', 'sf_room_restroom_cl'),
    NavEdge('sf_h_right_1', 'sf_room_restroom_cr'),
    NavEdge('sf_h_right_3', 'sf_room_vip_lounge'),
    NavEdge('sf_h_right_5', 'sf_room_faculty_lounge'),
    NavEdge('sf_h_right_5', 'sf_room_restroom_r1'),
    NavEdge('sf_h_right_6', 'sf_room_restroom_r2'),
    NavEdge('sf_h_right_7', 'sf_room_speech_lab'),
    NavEdge('sf_h_far_right', 'sf_room_bseed_left'),
    NavEdge('sf_h_spine', 'sf_room_main_stage'),
    NavEdge('sf_h_left_2', 'sf_room_bleacher_left'),
    NavEdge('sf_h_right_4', 'sf_room_bleacher_right'),
    NavEdge('sf_h_left_1', 'sf_room_guidance_counseling'),
    NavEdge('sf_h_left_2', 'sf_room_moot_court'),
    NavEdge('sf_h_left_3', 'sf_room_business'),
    NavEdge('sf_h_left_4', 'sf_room_classroom_l'),
    NavEdge('sf_h_left_5', 'sf_room_classroom_c'),
    NavEdge('sf_h_left_6', 'sf_room_classroom_r'),
    NavEdge('sf_h_right_2', 'sf_room_board'),
    NavEdge('sf_h_right_3', 'sf_room_hrmo'),
    NavEdge('sf_h_right_4', 'sf_room_faculty'),
    NavEdge('sf_h_right_5', 'sf_room_supply'),
    NavEdge('sf_h_right_6', 'sf_room_vp_planning'),
    NavEdge('sf_h_right_7', 'sf_room_evp'),
    NavEdge('sf_h_far_right', 'sf_room_bseed_right'),
    NavEdge('sf_v_deans', 'sf_room_deans'),
    NavEdge('sf_v_vpaa', 'sf_room_vpaa'),
    NavEdge('sf_v_mid', 'sf_room_president'),
  ];

  static const List<NavNode> thirdNodes = [
    NavNode('tf_entry_stairs_left', Offset(0.065, 0.300)),
    NavNode('tf_entry_stairs_right', Offset(0.935, 0.300)),
    NavNode('tf_entry_elevator', Offset(0.500, 0.300)),
    NavNode('tf_h_far_left', Offset(0.040, 0.300)),
    NavNode('tf_h_left_1', Offset(0.110, 0.300)),
    NavNode('tf_h_left_2', Offset(0.200, 0.300)),
    NavNode('tf_h_left_3', Offset(0.310, 0.300)),
    NavNode('tf_h_left_4', Offset(0.420, 0.300)),
    NavNode('tf_h_spine', Offset(0.500, 0.300)),
    NavNode('tf_h_right_1', Offset(0.560, 0.300)),
    NavNode('tf_h_right_2', Offset(0.620, 0.300)),
    NavNode('tf_h_right_3', Offset(0.680, 0.300)),
    NavNode('tf_h_right_4', Offset(0.745, 0.300)),
    NavNode('tf_h_right_5', Offset(0.810, 0.300)),
    NavNode('tf_h_right_6', Offset(0.875, 0.300)),
    NavNode('tf_h_far_right', Offset(0.960, 0.300)),
    NavNode('tf_low_far_left', Offset(0.040, 0.470)),
    NavNode('tf_low_left_1', Offset(0.110, 0.470)),
    NavNode('tf_low_left_2', Offset(0.200, 0.470)),
    NavNode('tf_low_left_3', Offset(0.310, 0.470)),
    NavNode('tf_low_spine', Offset(0.500, 0.470)),
    NavNode('tf_low_right_1', Offset(0.620, 0.470)),
    NavNode('tf_low_right_2', Offset(0.750, 0.470)),
    NavNode('tf_low_right_3', Offset(0.875, 0.470)),
    NavNode('tf_low_far_right', Offset(0.960, 0.470)),
    NavNode('tf_v_left_conn', Offset(0.110, 0.385)),
    NavNode('tf_v_spine_conn', Offset(0.500, 0.385)),
    NavNode('tf_v_right_conn', Offset(0.875, 0.385)),
    NavNode('tf_v_prayer_base', Offset(0.380, 0.200)),
    NavNode('tf_v_prayer_top', Offset(0.380, 0.090)),
    NavNode('tf_v_research_base', Offset(0.620, 0.200)),
    NavNode('tf_v_research_top', Offset(0.620, 0.090)),
    NavNode('tf_room_lrc1', Offset(0.065, 0.300)),
    NavNode('tf_room_library', Offset(0.250, 0.300)),
    NavNode('tf_room_lrc2', Offset(0.430, 0.300)),
    NavNode('tf_room_prayer', Offset(0.380, 0.130)),
    NavNode('tf_room_activity', Offset(0.500, 0.130)),
    NavNode('tf_room_research', Offset(0.620, 0.130)),
    NavNode('tf_room_restroom_l', Offset(0.555, 0.300)),
    NavNode('tf_room_restroom_r', Offset(0.580, 0.300)),
    NavNode('tf_room_classroom_1', Offset(0.650, 0.300)),
    NavNode('tf_room_classroom_2', Offset(0.710, 0.300)),
    NavNode('tf_room_classroom_3', Offset(0.770, 0.300)),
    NavNode('tf_room_classroom_4', Offset(0.825, 0.300)),
    NavNode('tf_room_classroom_5', Offset(0.880, 0.300)),
    NavNode('tf_room_sci_lab', Offset(0.930, 0.300)),
    NavNode('tf_room_classroom_6', Offset(0.980, 0.300)),
    NavNode('tf_room_bleacher_left', Offset(0.250, 0.600)),
    NavNode('tf_room_bleacher_right', Offset(0.750, 0.600)),
    NavNode('tf_room_main_stage', Offset(0.500, 0.750)),
  ];

  static const List<NavEdge> thirdEdges = [
    NavEdge('tf_h_far_left', 'tf_h_left_1'),
    NavEdge('tf_h_left_1', 'tf_h_left_2'),
    NavEdge('tf_h_left_2', 'tf_h_left_3'),
    NavEdge('tf_h_left_3', 'tf_h_left_4'),
    NavEdge('tf_h_left_4', 'tf_h_spine'),
    NavEdge('tf_h_spine', 'tf_h_right_1'),
    NavEdge('tf_h_right_1', 'tf_h_right_2'),
    NavEdge('tf_h_right_2', 'tf_h_right_3'),
    NavEdge('tf_h_right_3', 'tf_h_right_4'),
    NavEdge('tf_h_right_4', 'tf_h_right_5'),
    NavEdge('tf_h_right_5', 'tf_h_right_6'),
    NavEdge('tf_h_right_6', 'tf_h_far_right'),
    NavEdge('tf_entry_stairs_left', 'tf_h_far_left'),
    NavEdge('tf_entry_stairs_right', 'tf_h_far_right'),
    NavEdge('tf_entry_elevator', 'tf_h_spine'),
    NavEdge('tf_h_far_left', 'tf_low_far_left', blocked: true),
    NavEdge('tf_h_far_right', 'tf_low_far_right', blocked: true),
    NavEdge('tf_low_far_left', 'tf_low_left_1'),
    NavEdge('tf_low_left_1', 'tf_low_left_2'),
    NavEdge('tf_low_left_2', 'tf_low_left_3'),
    NavEdge('tf_low_left_3', 'tf_low_spine'),
    NavEdge('tf_low_spine', 'tf_low_right_1'),
    NavEdge('tf_low_right_1', 'tf_low_right_2'),
    NavEdge('tf_low_right_2', 'tf_low_right_3'),
    NavEdge('tf_low_right_3', 'tf_low_far_right'),
    NavEdge('tf_h_left_1', 'tf_v_left_conn'),
    NavEdge('tf_v_left_conn', 'tf_low_left_1'),
    NavEdge('tf_h_spine', 'tf_v_spine_conn'),
    NavEdge('tf_v_spine_conn', 'tf_low_spine'),
    NavEdge('tf_h_right_6', 'tf_v_right_conn'),
    NavEdge('tf_v_right_conn', 'tf_low_right_3'),
    NavEdge('tf_h_left_3', 'tf_v_prayer_base'),
    NavEdge('tf_v_prayer_base', 'tf_v_prayer_top'),
    NavEdge('tf_v_prayer_top', 'tf_room_prayer'),
    NavEdge('tf_h_right_2', 'tf_v_research_base'),
    NavEdge('tf_v_research_base', 'tf_v_research_top'),
    NavEdge('tf_v_research_top', 'tf_room_research'),
    NavEdge('tf_v_prayer_base', 'tf_room_activity'),
    NavEdge('tf_h_far_left', 'tf_room_lrc1'),
    NavEdge('tf_h_left_2', 'tf_room_library'),
    NavEdge('tf_h_left_4', 'tf_room_lrc2'),
    NavEdge('tf_h_right_1', 'tf_room_restroom_l'),
    NavEdge('tf_h_right_1', 'tf_room_restroom_r'),
    NavEdge('tf_h_right_2', 'tf_room_classroom_1'),
    NavEdge('tf_h_right_3', 'tf_room_classroom_2'),
    NavEdge('tf_h_right_4', 'tf_room_classroom_3'),
    NavEdge('tf_h_right_4', 'tf_room_classroom_4'),
    NavEdge('tf_h_right_5', 'tf_room_classroom_5'),
    NavEdge('tf_h_right_6', 'tf_room_sci_lab'),
    NavEdge('tf_h_far_right', 'tf_room_classroom_6'),
    NavEdge('tf_low_left_2', 'tf_room_bleacher_left'),
    NavEdge('tf_low_right_2', 'tf_room_bleacher_right'),
    NavEdge('tf_low_spine', 'tf_room_main_stage'),
  ];

  static const Map<String, String> roomToNode = {
    'gf_main_lobby': 'gf_room_main_lobby',
    'gf_ciso': 'gf_room_ciso',
    'gf_avr': 'gf_room_avr',
    'gf_medical': 'gf_room_medical',
    'gf_restroom_left': 'gf_room_restroom_top_left',
    'gf_restroom_center': 'gf_room_restroom_top_center',
    'gf_restroom_right': 'gf_room_restroom_top_right',
    'gf_ics': 'gf_room_ics',
    'gf_registrar': 'gf_room_registrar',
    'gf_record': 'gf_room_record',
    'gf_vp_admin': 'gf_room_vp_admin',
    'gf_crim_lab': 'gf_room_crim_lab',
    'gf_icje': 'gf_room_icje',
    'gf_sldo': 'gf_room_sldo',
    'gf_scholarship': 'gf_room_scholarship',
    'gf_ojt': 'gf_room_ojt',
    'gf_accreditation': 'gf_room_accreditation',
    'gf_elevator': 'gf_room_elevator',
    'gf_dressing': 'gf_room_dressing',
    'gf_music': 'gf_room_music',
    'gf_dance': 'gf_room_dance',
    'gf_barracks': 'gf_room_barracks',
    'gf_mb105': 'gf_room_mb105',
    'gf_mb103': 'gf_room_mb103',
    'gf_mpr': 'gf_room_mpr',
    'gf_midwifery': 'gf_room_midwifery',
    'gf_pfom': 'gf_room_pfom',
    'gf_ias': 'gf_room_ias',
    'gf_ite': 'gf_room_ite',
    'gf_ibfs': 'gf_room_ibfs',
    'gf_ihs': 'gf_room_ihs',
    'gf_training': 'gf_room_training',
    'gf_cr_left1': 'gf_room_cr_left1',
    'gf_cr_left2': 'gf_room_cr_left2',
    'gf_cr_right1': 'gf_room_cr_right1',
    'gf_cr_right2': 'gf_room_cr_right2',
    'sf_main_stage': 'sf_room_main_stage',
    'sf_guidance_testing': 'sf_room_guidance_test',
    'sf_computer_lab': 'sf_room_comp_lab',
    'sf_computer_room_1': 'sf_room_comp_room1',
    'sf_computer_room_2': 'sf_room_comp_room2',
    'sf_computer_room_3': 'sf_room_comp_room3',
    'sf_restroom_left': 'sf_room_restroom_cl',
    'sf_restroom_center_left': 'sf_room_restroom_cl',
    'sf_restroom_center_right': 'sf_room_restroom_cr',
    'sf_restroom_right': 'sf_room_restroom_r1',
    'sf_vip_lounge': 'sf_room_vip_lounge',
    'sf_faculty_lounge': 'sf_room_faculty_lounge',
    'sf_speech_lab': 'sf_room_speech_lab',
    'sf_bseed_left': 'sf_room_bseed_left',
    'sf_bseed_right': 'sf_room_bseed_right',
    'sf_guidance_counseling': 'sf_room_guidance_counseling',
    'sf_moot_court': 'sf_room_moot_court',
    'sf_business_center': 'sf_room_business',
    'sf_classroom_left': 'sf_room_classroom_l',
    'sf_classroom_center': 'sf_room_classroom_c',
    'sf_classroom_right': 'sf_room_classroom_r',
    'sf_board_room': 'sf_room_board',
    'sf_hrmo': 'sf_room_hrmo',
    'sf_faculty_room': 'sf_room_faculty',
    'sf_supply': 'sf_room_supply',
    'sf_vp_planning': 'sf_room_vp_planning',
    'sf_evp': 'sf_room_evp',
    'sf_deans': 'sf_room_deans',
    'sf_vpaa': 'sf_room_vpaa',
    'sf_president': 'sf_room_president',
    'sf_deck_canopy': 'sf_entry_deck',
    'tf_library': 'tf_room_library',
    'tf_lrc1': 'tf_room_lrc1',
    'tf_lrc2': 'tf_room_lrc2',
    'tf_prayer': 'tf_room_prayer',
    'tf_activity': 'tf_room_activity',
    'tf_research': 'tf_room_research',
    'tf_restroom_left': 'tf_room_restroom_l',
    'tf_restroom_right': 'tf_room_restroom_r',
    'tf_classroom_1': 'tf_room_classroom_1',
    'tf_classroom_2': 'tf_room_classroom_2',
    'tf_classroom_3': 'tf_room_classroom_3',
    'tf_classroom_4': 'tf_room_classroom_4',
    'tf_classroom_5': 'tf_room_classroom_5',
    'tf_classroom_6': 'tf_room_classroom_6',
    'tf_science_lab': 'tf_room_sci_lab',
    'tf_elevator': 'tf_entry_elevator',
    'tf_main_stage': 'tf_room_main_stage',
    'tf_bleacher_left': 'tf_room_bleacher_left',
    'tf_bleacher_right': 'tf_room_bleacher_right',
  };

  static List<NavNode> getNodes(int floor) {
    switch (floor) {
      case 0:
        return groundNodes;
      case 1:
        return secondNodes;
      case 2:
        return thirdNodes;
      default:
        return groundNodes;
    }
  }

  static List<NavEdge> getEdges(int floor) {
    switch (floor) {
      case 0:
        return groundEdges;
      case 1:
        return secondEdges;
      case 2:
        return thirdEdges;
      default:
        return groundEdges;
    }
  }

  static String? getDefaultStartNode(int floor) {
    switch (floor) {
      case 0:
        return 'gf_entry_driveway';
      case 1:
        return 'sf_entry_stairs_left';
      case 2:
        return 'tf_entry_stairs_left';
      default:
        return 'gf_entry_driveway';
    }
  }
}