// lib/services/room_catalog.dart
class RoomCatalog {
  static const Map<String, List<Map<String, String>>> allRooms = {
    'Ground Floor': [
      {'name': 'Main Lobby', 'id': 'gf_main_lobby'},
      {'name': 'Drive Way', 'id': 'gf_drive_way'},
      {'name': 'Scholarship and Welfare Office', 'id': 'gf_scholarship'},
      {'name': 'OJT & Placement / Alumni Affairs Office', 'id': 'gf_ojt'},
      {'name': 'Accreditation Room', 'id': 'gf_accreditation'},
      {'name': 'Record Section Registrar', 'id': 'gf_record'},
      {"name": "Registrar's Office", 'id': 'gf_registrar'},
      {'name': 'VP Admin and Finance', 'id': 'gf_vp_admin'},
      {'name': 'Criminology Laboratory', 'id': 'gf_crim_lab'},
      {'name': 'Institute of Criminal Justice Education', 'id': 'gf_icje'},
      {'name': 'Student Life and Development Office', 'id': 'gf_sldo'},
      {'name': 'CISO', 'id': 'gf_ciso'},
      {'name': 'Audio Visual Room', 'id': 'gf_avr'},
      {'name': 'Dressing Room', 'id': 'gf_dressing'},
      {'name': 'Music Room', 'id': 'gf_music'},
      {'name': 'Dance Studio', 'id': 'gf_dance'},
      {'name': 'Maintenance Student Assistant Personnel Barracks', 'id': 'gf_barracks'},
      {'name': 'Medical & Dental Clinic', 'id': 'gf_medical'},
      {'name': 'Rest Room (Left Wing)', 'id': 'gf_restroom_left'},
      {'name': 'Rest Room (Center)', 'id': 'gf_restroom_center'},
      {'name': 'Rest Room (Right)', 'id': 'gf_restroom_right'},
      {'name': 'MB 105', 'id': 'gf_mb105'},
      {'name': 'MB 103 / Demo Room', 'id': 'gf_mb103'},
      {'name': 'Multi-Purpose Room', 'id': 'gf_mpr'},
      {'name': 'Midwifery Laboratory', 'id': 'gf_midwifery'},
      {'name': 'Physical Facilities Operation & Maintenance (PFOM)', 'id': 'gf_pfom'},
      {'name': 'Institute of Arts & Sciences', 'id': 'gf_ias'},
      {'name': 'Institute of Teacher Education', 'id': 'gf_ite'},
      {'name': 'Institute of Business & Financial Services', 'id': 'gf_ibfs'},
      {'name': 'Institute of Health Sciences', 'id': 'gf_ihs'},
      {"name": "TCGC Dev't Training Center", 'id': 'gf_training'},
      {'name': 'Institute of Computer Studies', 'id': 'gf_ics'},
      {'name': 'CR (Left 1)', 'id': 'gf_cr_left1'},
      {'name': 'CR (Left 2)', 'id': 'gf_cr_left2'},
      {'name': 'CR (Right 1)', 'id': 'gf_cr_right1'},
      {'name': 'CR (Right 2)', 'id': 'gf_cr_right2'},
      {'name': 'Elevator', 'id': 'gf_elevator'},
    ],
    '2nd Floor': [
      {'name': 'Main Stage', 'id': 'sf_main_stage'},
      {'name': 'Guidance Testing Center', 'id': 'sf_guidance_testing'},
      {'name': 'Sub-Lobby', 'id': 'sf_sub_lobby'},
      {'name': 'Computer Laboratory', 'id': 'sf_computer_lab'},
      {'name': 'Computer Room (1)', 'id': 'sf_computer_room_1'},
      {'name': 'Computer Room (2)', 'id': 'sf_computer_room_2'},
      {'name': 'Computer Room (3)', 'id': 'sf_computer_room_3'},
      {'name': 'Rest Room (Left)', 'id': 'sf_restroom_left'},
      {'name': 'Rest Room (Center Left)', 'id': 'sf_restroom_cl'},
      {'name': 'Rest Room (Center Right)', 'id': 'sf_restroom_cr'},
      {'name': 'Rest Room (Right)', 'id': 'sf_restroom_r1'},
      {'name': 'VIP Lounge', 'id': 'sf_vip_lounge'},
      {'name': 'Faculty and Staff Lounge', 'id': 'sf_faculty_lounge'},
      {'name': 'Speech Lab', 'id': 'sf_speech_lab'},
      {'name': 'BSEED Simulation Room (Left)', 'id': 'sf_bseed_left'},
      {'name': 'BSEED Simulation Room (Right)', 'id': 'sf_bseed_right'},
      {'name': 'Guidance Counseling Room', 'id': 'sf_guidance_counsel'},
      {'name': 'Moot Court', 'id': 'sf_moot_court'},
      {'name': 'Business Center', 'id': 'sf_business_center'},
      {'name': 'Classroom (Left)', 'id': 'sf_classroom_left'},
      {'name': 'Class Room (Center)', 'id': 'sf_classroom_center'},
      {'name': 'Class Room (Right)', 'id': 'sf_classroom_right'},
      {'name': 'Board Room', 'id': 'sf_board_room'},
      {'name': 'Human Resource Management Office', 'id': 'sf_hrmo'},
      {'name': 'Faculty Room', 'id': 'sf_faculty_room'},
      {'name': 'Supply Office', 'id': 'sf_supply'},
      {'name': 'VP for Planning', 'id': 'sf_vp_planning'},
      {'name': 'Executive Vice President Office', 'id': 'sf_evp'},
      {"name": "Dean's Office", 'id': 'sf_deans'},
      {'name': 'VP for Academic Affairs', 'id': 'sf_vpaa'},
      {'name': 'Office of the President', 'id': 'sf_president'},
      {'name': 'Deck Canopy', 'id': 'sf_deck_canopy'},
      {'name': 'Bleacher (Left Wing)', 'id': 'sf_bleacher_left'},
      {'name': 'Bleacher (Right Wing)', 'id': 'sf_bleacher_right'},
    ],
    '3rd Floor': [
      {'name': 'Library', 'id': 'tf_library'},
      {'name': 'LRC Extension 1', 'id': 'tf_lrc1'},
      {'name': 'LRC Extension 2', 'id': 'tf_lrc2'},
      {'name': 'Prayer Room', 'id': 'tf_prayer'},
      {'name': 'Activity Area', 'id': 'tf_activity'},
      {'name': 'Research Extension Development', 'id': 'tf_research'},
      {'name': 'Rest Room (Left)', 'id': 'tf_restroom_left'},
      {'name': 'Rest Room (Right)', 'id': 'tf_restroom_right'},
      {'name': 'Classroom (1)', 'id': 'tf_classroom_1'},
      {'name': 'Classroom (2)', 'id': 'tf_classroom_2'},
      {'name': 'Classroom (3)', 'id': 'tf_classroom_3'},
      {'name': 'Classroom (4)', 'id': 'tf_classroom_4'},
      {'name': 'Classroom (5)', 'id': 'tf_classroom_5'},
      {'name': 'Classroom (6)', 'id': 'tf_classroom_6'},
      {'name': 'Science Laboratory', 'id': 'tf_science_lab'},
      {'name': 'Elevator', 'id': 'tf_elevator'},
      {'name': 'Main Stage', 'id': 'tf_main_stage'},
      {'name': 'Bleacher (Left Wing)', 'id': 'tf_bleacher_left'},
      {'name': 'Bleacher (Right Wing)', 'id': 'tf_bleacher_right'},
    ],
  };

  static const List<String> floorKeys = ['Ground Floor', '2nd Floor', '3rd Floor'];

  static String? roomNameById(String roomId) {
    for (final rooms in allRooms.values) {
      for (final room in rooms) {
        if (room['id'] == roomId) return room['name'];
      }
    }
    return null;
  }
}
